openapi: 3.0.0
info:
  title: 06-Jobs-Api
  contact : {}
  version: 1.0.0
servers:
  - url: https://jobs-api-pg88.onrender.com
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: RegisterUser
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Rajath
                email: rajathnh1aa34@gmail.com
                password: Raj1athnh@1
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: rajathnh1@gmail.com
                password: Raj1athnh@1
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /jobs:
    post:
      tags:
        - Jobs
      summary: Create Job
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                company: netflix
                position: back end dev
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Jobs
      summary: getalljobs
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /jobs/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The job ID
    get:
      tags:
        - Jobs
      summary: getsinglejob
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - Jobs
      summary: update Job
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                company: kaj
                position: front end dev
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Jobs
      summary: delete user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}